# Generated by Django 3.0.7 on 2020-07-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200705_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
