# Generated by Django 3.0.7 on 2020-07-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200705_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spending',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='spending',
            name='category',
        ),
        migrations.RemoveField(
            model_name='spending',
            name='name',
        ),
        migrations.AddField(
            model_name='spending',
            name='groceries',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='spending',
            name='invoices',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='spending',
            name='others',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='spending',
            name='rent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='spending',
            name='shopping',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='saving',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
