# Generated by Django 3.0.7 on 2020-07-06 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200705_2029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spending',
        ),
    ]
