# Generated by Django 3.0.7 on 2020-07-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200706_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='spending',
        ),
        migrations.AddField(
            model_name='saving',
            name='spending',
            field=models.ManyToManyField(null=True, to='users.Spending'),
        ),
    ]
