# Generated by Django 3.0.7 on 2020-07-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200706_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='spending',
            field=models.ManyToManyField(to='users.Spending'),
        ),
    ]
