# Generated by Django 3.0.7 on 2020-07-06 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200706_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='buget',
        ),
        migrations.RemoveField(
            model_name='saving',
            name='spending',
        ),
    ]
