# Generated by Django 3.0.7 on 2020-07-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200706_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='buget',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RON', 'RON'), ('MDL', 'MDL')], max_length=100, null=True),
        ),
    ]
