# Generated by Django 3.0.7 on 2020-07-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_buget_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buget',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RON', 'RON'), ('MDL', 'MDL')], default='USD', max_length=100),
        ),
    ]
