# Generated by Django 3.0.7 on 2020-07-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200707_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buget',
            name='amount',
            field=models.FloatField(),
        ),
    ]
