# Generated by Django 3.0.7 on 2020-07-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200707_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buget',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='spending',
            name='amount',
            field=models.FloatField(),
        ),
    ]
