# Generated by Django 3.0.7 on 2020-08-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20200719_1108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saving',
        ),
    ]
