# Generated by Django 3.0.7 on 2020-08-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_note_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
