# Generated by Django 3.0.7 on 2020-08-13 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20200813_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
