# Generated by Django 3.0.7 on 2020-08-15 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0030_auto_20200814_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='currency',
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('AED', 'AED'), ('AUD', 'AUD'), ('BRL', 'BRL'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('CLP', 'CLP'), ('CNY', 'CNY'), ('COP', 'COP'), ('CZK', 'CZK'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('HKD', 'HKD'), ('HUF', 'HUF'), ('IDR', 'IDR'), ('ILS', 'ILS'), ('INR', 'INR'), ('JPY', 'JPY'), ('KRW', 'KRW'), ('MDL', 'MDL'), ('MXN', 'MXN'), ('MYR', 'MYR'), ('NOK', 'NOK'), ('NZD', 'NZD'), ('PHP', 'PHP'), ('PLN', 'PLN'), ('RON', 'RON'), ('RUB', 'RUB'), ('SAR', 'SAR'), ('SEK', 'SEK'), ('SGD', 'SGD'), ('THB', 'THB'), ('TRY', 'TRY'), ('TWD', 'TWD'), ('USD', 'USD'), ('ZAR', 'ZAR')], default='USD', max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
