# Generated by Django 3.0.7 on 2020-08-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20200815_0838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
