# Generated by Django 3.0.7 on 2020-08-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='recurrent',
            field=models.BooleanField(default=False),
        ),
    ]
