# Generated by Django 3.0.7 on 2020-08-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_spending_recurrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='recurrent',
            field=models.BooleanField(default=False),
        ),
    ]
