# Generated by Django 3.0.7 on 2020-07-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment_text',
        ),
    ]
